// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface IContactFields {
  /** Name */
  name: string;

  /** Link */
  link: string;
}

export interface IContact extends Entry<IContactFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'contact';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IContactsFields {
  /** Email */
  email: string;

  /** CV */
  cv: string;

  /** CV visible */
  cvVisible: boolean;

  /** Links */
  links?: IContact[] | undefined;
}

export interface IContacts extends Entry<IContactsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'contacts';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IProjectFields {
  /** Name */
  name: string;

  /** Tools */
  tools: string[];

  /** Link */
  link?: string | undefined;

  /** Git link */
  gitLink: string;

  /** Image */
  image: Asset;
}

export interface IProject extends Entry<IProjectFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'project';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ISeoFields {
  /** Title */
  title: string;

  /** Description */
  description: string;

  /** Image */
  image?: Asset | undefined;

  /** Keywords */
  keywords?: string[] | undefined;

  /** OG Title */
  ogTitle?: string | undefined;

  /** OG Description */
  ogDescription?: string | undefined;

  /** OG Image */
  ogImage?: Asset | undefined;
}

export interface ISeo extends Entry<ISeoFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'seo';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ISkillsFields {
  /** Title */
  title: string;

  /** Skill */
  skill: string[];
}

export interface ISkills extends Entry<ISkillsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'skills';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE = 'contact' | 'contacts' | 'project' | 'seo' | 'skills';

export type LOCALE_CODE = 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
